services:
    mariadb:
        image: mariadb:10.6
        environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: vteam
          MYSQL_USER: vteam01
          MYSQL_PASSWORD: vteam
        ports:
          - "3306:3306"
        volumes:
          - ./db:/docker-entrypoint-initdb.d
          - ./csv:/csv
        restart: always
