name: Run API Tests

on:
  push:
    branches: [feature/actions]
  pull_request:
    branches: [feature/actions]

jobs:
  test-api:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: vteam
          MYSQL_USER: vteam01
          MYSQL_PASSWORD: vteam
        ports:
          - "3306:3306"

    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Insert database data
        run: mariadb -h 127.0.0.1 -P 3306 -u vteam01 -pvteam vteam < db/init.sql
      - name: Run tests
        run: npm test -- --watchAll=false
